# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "deploy" ]
  pull_request:
    branches: [ "deploy" ]

jobs:
  versioning:
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
  
      - name: Calculate version
        id: calculate-version
        uses: bitshifted/git-auto-semver@v1
        with:
          create_tag: true
          tag_prefix: 'v'
  
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
        
      - name: Build Go binary with version
        run: |
          go build -o snippetbox -ldflags "-X main.version=${{ steps.calculate-version.outputs.version-string }}" ./cmd/web
      
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.calculate-version.outputs.version-string }}
          files: |
            snippetbox
          name: Release v${{ steps.calculate-version.outputs.version-string }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

